### ISSUE TITLE
Facing issues while adding policies via json/yaml file

### ISSUE THREAD

**Issue by Gayathri071123** [apigee/apigee-templater#7]
Good Day,
I'm  able to set and authenticate my existing GCP project and able to create and deploy the proxy successfully.

But while trying to add policies via json/yaml file as input using APIGEE Templater we are running into below issues.

Passed input file as httpbin.json that has spike arrest policy configured:

[httpbin.json](https://github.com/apigee/apigee-templater/files/13283065/httpbin.json)

Passed the input file as openapiyaml.yaml:

[openapi.json](https://github.com/apigee/apigee-templater/files/13283066/openapi.json)
<img width="953" alt="Error" src="https://github.com/apigee/apigee-templater/assets/150167291/3692f5b5-7134-43f6-b840-f1e0b8d7f1d6">

It would be really great if you can help me to resolve this issue.

Thanks.

**Comment by tyayers** [comment]
Hi, thanks for testing, will take a closer look and get back to you..

**Comment by tyayers** [comment]
Hi, I tested the template json and it works fine for me, the issue above is probably because you don't have any default credentials to authenticate to GCP with.. The easiest way is to just run the command `gcloud auth application-default login`in the same shell, you will then be asked to authorize the CLI access to use your user account for automation in our shell environment, see more info here: https://cloud.google.com/docs/authentication/provide-credentials-adc

**Comment by tyayers** [comment]
You can also authenticate with a service account key file with the `-k` parameter.

**Comment by tyayers** [comment]
This was probably an incorrect error message, several bugs fixed last week, should be working now (in case still having issues open a new issue with the new error message).
